name: CI

on: [push, pull_request]

jobs:
  Build_image:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build  -t github-scripts .
